### ISSUE TITLE
re-export via single module

### ISSUE THREAD

**Issue by IlyaSemenov** [chase-moskal/redcrypto#4]
Can we please re-export the functions via a single module entry instead of file-per-function? Such as:

```ts
import { tokenSign } from "redcrypto"
```

with ESM exports and modern bundlers that should perfectly tree-shake.

Perhaps, it would be two files:
1) `redcrypto` (all exports)
2) `redcrypo/client` (exports only available in the browser)

**Comment by chase-moskal** [comment]
hello, i've made the requested addition in redcrypto v0.0.5

everything is now re-exported at `x/index.js`, which is now the main module:

```ts
import {tokenSign} from "redcrypto"
```

and the clientside functionality is at `x/client.js`:

```ts
import {tokenDecode} from "redcrypto/x/client.js"
```

:warning: note that it's exposed at `redcrypto/x/client.js` instead of `redcrypto/client`.

@IlyaSemenov let me know if this works for you -- i don't have time today to actually verify it :)
